name: Defense News Scraper

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday 9 AM UTC
  workflow_dispatch:     # Manual run button
    inputs:
      days:
        description: 'Days to look back (1-30)'
        required: false
        default: '7'
        type: string

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run scraper
      run: |
        python simple_scraper.py --manual --days ${{ github.event.inputs.days || '7' }}
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: defense-news-report-${{ github.event.inputs.days || '7' }}days
        path: "defense_news_*.md"
        retention-days: 30
